/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An address on a blockchain
 */
export interface BlockchainAddress {
  address: string;
  /**
   * @minItems 1
   */
  tags: [
    "eoa" | "safe" | "creator" | "factory" | "proxy" | "contract",
    ...("eoa" | "safe" | "creator" | "factory" | "proxy" | "contract")[],
  ];
  name?: string;
  [k: string]: unknown;
}
