/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A project is a collection of artifacts
 */
export interface Project {
  version: number;
  name: string;
  display_name: string;
  description?: string;
  websites?: URL[];
  social?: SocialProfile;
  github?: URL[];
  npm?: URL[];
  cargo?: URL[];
  pypi?: URL[];
  go?: URL[];
  open_collective?: URL[];
  blockchain?: BlockchainAddress[];
  defillama?: URL[];
  comments?: string[];
  [k: string]: unknown;
}
/**
 * A generic URL
 */
export interface URL {
  url: string;
  [k: string]: unknown;
}
/**
 * All social profile
 */
export interface SocialProfile {
  farcaster?: URL[];
  medium?: URL[];
  mirror?: URL[];
  telegram?: URL[];
  twitter?: URL[];
  [k: string]: unknown;
}
/**
 * An address on a blockchain
 */
export interface BlockchainAddress {
  address: string;
  /**
   * @minItems 1
   */
  tags: [
    (
      | "bridge"
      | "contract"
      | "creator"
      | "deployer"
      | "eoa"
      | "factory"
      | "proxy"
      | "safe"
      | "wallet"
    ),
    ...(
      | "bridge"
      | "contract"
      | "creator"
      | "deployer"
      | "eoa"
      | "factory"
      | "proxy"
      | "safe"
      | "wallet"
    )[],
  ];
  /**
   * @minItems 1
   */
  networks: [
    (
      | "any_evm"
      | "arbitrum_one"
      | "automata"
      | "base"
      | "bob"
      | "cyber"
      | "frax"
      | "ham"
      | "kroma"
      | "linea"
      | "lisk"
      | "lyra"
      | "mainnet"
      | "mantle"
      | "matic"
      | "metal"
      | "mint"
      | "mode"
      | "optimism"
      | "orderly"
      | "pgn"
      | "polynomial"
      | "polygon_zkevm"
      | "race"
      | "redstone"
      | "scroll"
      | "shape"
      | "swan"
      | "unichain"
      | "worldchain"
      | "xterio"
      | "zksync_era"
      | "zora"
    ),
    ...(
      | "any_evm"
      | "arbitrum_one"
      | "automata"
      | "base"
      | "bob"
      | "cyber"
      | "frax"
      | "ham"
      | "kroma"
      | "linea"
      | "lisk"
      | "lyra"
      | "mainnet"
      | "mantle"
      | "matic"
      | "metal"
      | "mint"
      | "mode"
      | "optimism"
      | "orderly"
      | "pgn"
      | "polynomial"
      | "polygon_zkevm"
      | "race"
      | "redstone"
      | "scroll"
      | "shape"
      | "swan"
      | "unichain"
      | "worldchain"
      | "xterio"
      | "zksync_era"
      | "zora"
    )[],
  ];
  name?: string;
  [k: string]: unknown;
}
