/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * All social profile
 */
export interface SocialProfile {
  farcaster?: URL[];
  medium?: URL[];
  mirror?: URL[];
  telegram?: URL[];
  twitter?: URL[];
  [k: string]: unknown;
}
/**
 * A generic URL
 */
export interface URL {
  url: string;
  [k: string]: unknown;
}
